"""
Problem
In DNA strings, symbols 'A' and 'T' are complements of each other, as are 'C' and 'G'.

The reverse complement of a DNA string s is the string sc formed by reversing the symbols of s, then taking the complement of each symbol (e.g., the reverse complement of "GTCA" is "TGAC").

Given: A DNA string s of length at most 1000 bp.

Return: The reverse complement sc of s.
"""

from Bio.Seq import Seq
#Here is the input
dna_seq="TCAAAAAGATATGGATTTACTTCCTTTTTTCAGCGGTTGTTCTGGTTGCCTCGTTCGAACCCCGGGATGATGGACTATTTTGTGACTCGAGGGTATTATGTGAAGCCACTATGATACCCCGGGACTCTTACCCCTGTGTACGTCATAGGGACTAAGATACATTCGGGTCCTATTTATGGGTGAGACGCCTCGGGAAGACACGATCACCCCCAGCGCACGACCCAAACTGAACGTTCCGCCTAATCTGCGAAGGCCAAAGAGTACGGAAGAGATCTTATGTACTTGATGGAGTCCGGATCTACCTTGCTTCACGTCCCTCCCGCTGGCCCAACGCTTGATCGACCATGACCGTCTCGAAGCCTAAGGGGCACGACGTTCCGATAAGAATTCGGGTCGTTCTTGCACGTCCAGCTCCCAGGGTCTCTTGTGAGCTCCGCCTGTGCGAAAAGGGCCCTCGTAAAAACTAAACGTGTAGGTCATAAAGAAAACGTGAATGGTATGGGATTCTATCAGCTGGGTCACCCGGATCAGCATAACTTTGCGCGAAATCCTACCGACAGCCCCTAGGACGCTGAACAACGCGTTCTCGCGAATTGTACATGGATTCTGCAGGTTTCCGGCCAGAGTGTAGATTCACCTTATAGCCGGGTAAAAACCCGGCGGTCGCTCGTACGCAAAAAGTGTCCTTCTTTATAACTGACAGTGGGGACTTGACGTAGCGGTGAGTTCTTCAGGAATCTATTTTGCAAGACACAAGAGACGGCTTTGGCATGTTCAAGAGTACAATCCGCATAGATGCAGCGGGGGTTGTACGGGCTGTTCAAAGACAGAGTTCAGCGTTCGTCCCATTTTCGATATCCTAGCCGTCAAAATTTAACATGATAGCAATTCGTC"

my_seq= Seq(dna_seq) # Then we create an "Seq" object
my_seq_compl= my_seq.reverse_complement() #Here the package of biopython uses a function to formulate the reverse complement of "my_seq"
print(my_seq_compl) # This step is neccesary to see the complete reverse complement sequence.
